name: 'Percy for Origami Component System'
description: 'A GitHub action to visually test Origami Components with Percy'
runs:
  using: 'node12'
  main: 'src/index.js'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
