{{=<% %>=}}
name: percy
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    paths:
      - "package.json"
      - "package-lock.json"
      - "components/**"
      - "!components/**/*.md"
  push:
    branches: main
    paths:
      - "package.json"
      - "package-lock.json"
      - "components/**"
      - "!components/**/*.md"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.set-matrix.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          volta-version: "1.0.8"
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Find components affected by changes
        id: percy-changes
        run: |
          changes=()

          for component in components/*/; do
            RESULT=$(WORKSPACE=$component node ./scripts/should-percy-run.js | grep "\-RESULT:" | cut -d ":" -f 2)
            if [[ $RESULT = 'true' ]]; then
              echo "$component is affected changes, adding to percy run list."
              changes+=("$component")
            fi
          done

          json_array=$(jq -n '$ARGS.positional' --args "${changes[@]}");
          echo "Changes:\n$json_array:";

          echo "CHANGES=$(echo ${json_array})" >> "$GITHUB_OUTPUT";
      - name: Set Matrix
        id: set-matrix
        run: |
          MATRIX=$(echo '${{ steps.percy-changes.outputs.changes }}'  | jq 'map({component: .})' | tr '\n' ' ')
          echo "CHANGES=$(echo "$MATRIX")" >> "$GITHUB_OUTPUT";
  run-percy:
      if: ${{ needs.changes.outputs.components != '[]' && needs.changes.outputs.components != '' }}
      needs: changes
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          component: ${{ fromJson(needs.changes.outputs.components) }}
      steps:
        - run: |
            echo "Running percy for ${{ matrix.component }}"
