{{=<% %>=}}
name: test
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main, 2025-release]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
        <%#projects%>
          <%& workspace %>:
            - '<%& workspace %>/**'
        <%/projects%>
  setup:
    if: ${{ needs.changes.outputs.components != '[]' && needs.changes.outputs.components != '' }}
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          volta-version: "1.0.8"
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Configure Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          npm config set registry=https://npm.packages.ft.com/financial-times-internal-releases/
          npm config set //npm.packages.ft.com/financial-times-internal-releases/:_authToken=${CLOUDSMITH_API_KEY}
      - name: Install node modules
        run: npm ci
  test:
    if: ${{ needs.changes.outputs.components != '[]' && needs.changes.outputs.components != '' }}
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.changes.outputs.components) }}
    steps:
      - run: npm run -w ${{ matrix.component }} lint --if-present
      - run: npm run -w ${{ matrix.component }} build --if-present
      - run: npm run -w ${{ matrix.component }} test --if-present
  test-results:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: All tests passing
        if: ${{ needs.test.result == 'success' }}
        run: exit 0
      - name: Some tests failing
        if: ${{ needs.test.result == 'failure' }}
        run: exit 1
