{{=<% %>=}}
name: test <%& workspace %>
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-<%& workspace %>
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci && npm i
    - run: npm run -w <%& workspace %> lint --if-present
    - run: npm run -w <%& workspace %> build --if-present
    - run: npm run -w <%& workspace %> test --if-present
