{{=<% %>=}}
name: test
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
        <%#projects%>
          <%& workspaceFilename %>:
            - '<%& workspace %>/**'
        <%/projects%>
  test-changes:
    runs-on: ubuntu-latest
    env:
      COMPONENTS: ${{ fromJson(needs.changes.outputs.components) }}
    steps:
      - run: echo $COMPONENTS
  test:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          volta-version: "1.0.8"
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run -w <%& workspace %> lint --if-present
      - run: npm run -w <%& workspace %> build --if-present
      - run: npm run -w <%& workspace %> test --if-present
