name: check if monorepo config needs regenerated (npm run regenerate)
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check-monorepo-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: actions/cache@v4
        with:
          volta-version: "1.0.8"
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Configure Cloudsmith
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: |
          npm config set registry=https://npm.packages.ft.com/financial-times-internal-releases/
          npm config set //npm.packages.ft.com/financial-times-internal-releases/:_authToken=${CLOUDSMITH_API_KEY}
      - name: Install node modules
        run: npm ci
      - run: npm run regenerate
      - run: ./scripts/check-for-changes.bash
