on:
  issues:
    types: [opened]

name: Create Jira Ticket

jobs:
  create-jira-ticket:
    name: Jira Ticket
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: OR
          issuetype: Support Request
          summary: "Github Issue: ${{ github.event.issue.title }}"
          description: ${{ github.event.issue.url }}
          fields: '{"labels": ["test"]}'
      - name: Log created ticket
        run: echo "Ticket ${{ steps.create.outputs.issue }} was created"
