name: Percy components/o-stepped-progress
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
     - "components/o-stepped-progress/package.json"
     - "components/o-stepped-progress/package-lock.json"
     - "components/o-stepped-progress/origami.json"
     - "components/o-stepped-progress/main.js"
     - "components/o-stepped-progress/main.scss"
     - "components/o-stepped-progress/demos/**"
     - "components/o-stepped-progress/src/**"
  push:
    branches: main
    paths:
     - "components/o-stepped-progress/package.json"
     - "components/o-stepped-progress/package-lock.json"
     - "components/o-stepped-progress/origami.json"
     - "components/o-stepped-progress/main.js"
     - "components/o-stepped-progress/main.scss"
     - "components/o-stepped-progress/demos/**"
     - "components/o-stepped-progress/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
        registry-url: 'https://origami-npm-registry-prototype.herokuapp.com'
    - run: npm ci
    - uses: ./actions/percy/
      with:
        # To comment as the Origami Fox mascot GitHub user
        github-token: ${{secrets.ORIGAMI_FOX_ACCESS_TOKEN}}
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_STEPPED_PROGRESS }}
        WORKSPACE: components/o-stepped-progress
