name: Percy
on: 
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
  push:
    branches: $default-branch
jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Financial-Times/origami-percy@v1
      with:
        github-token: ${{secrets.ORIGAMI_FOX_ACCESS_TOKEN}} # To comment as the Fox mascot GitHub user
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
