name: percy
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    paths:
      - "package.json"
      - "package-lock.json"
      - "components/**"
      - "!components/**/*.md"
  push:
    branches: main
    paths:
      - "package.json"
      - "package-lock.json"
      - "components/**"
      - "!components/**/*.md"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          volta-version: "1.0.8"
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: |
          git branch
          changes=()
          for component in components/*/; do
            WORKSPACE=$component node ./scripts/should-percy-run.js
            if [[ $? -eq 0 ]]; then
              changes+=("$component")
            fi
          done
          echo "$changes";
          echo "CHANGES=$changes" >> $GITHUB_OUTPUT;

