name: percy components/o-normalise
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}-components/o-normalise
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "components/o-normalise/**"
  push:
    branches: main
    paths:
      - "components/o-normalise/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
    - run: npm ci
    - run: node ./actions/percy/src/index.js
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_NORMALISE }}
        WORKSPACE: components/o-normalise
