name: percy components/o-header
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}-components/o-header
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: main
    paths:
      - "components/o-header/package.json"
      - "components/o-header/package-lock.json"
      - "components/o-header/origami.json"
      - "components/o-header/main.js"
      - "components/o-header/main.scss"
      - "components/o-header/demos/**"
      - "components/o-header/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
    - run: npm ci
    - run: node ./scripts/percy.mjs
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_HEADER }}
        WORKSPACE: components/o-header
