name: Percy
on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "bower.json"
      - "origami.json"
      - "main.js"
      - "main.scss"
      - "demos/**"
      - "src/**"
  push:
    branches: master
    paths:
      - "bower.json"
      - "origami.json"
      - "main.js"
      - "main.scss"
      - "demos/**"
      - "src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Financial-Times/origami-percy@v1
        with:
          github-token: ${{secrets.ORIGAMI_FOX_ACCESS_TOKEN}} # To comment as the Fox mascot GitHub user
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
