name: Percy
on: 
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
  push:
    branches: master
jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - if: contains(github.event.pull_request.labels.*.name, 'percy') || endsWith(github.ref, '/master')
      name: Percy Test
      uses: Financial-Times/origami-percy@master
      with:
        github-token: ${{secrets.ORIGAMI_FOX_ACCESS_TOKEN}}
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
