name: percy components/o-stepped-progress
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}-components/o-stepped-progress
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: main
    paths:
      - "components/o-stepped-progress/package.json"
      - "components/o-stepped-progress/package-lock.json"
      - "components/o-stepped-progress/origami.json"
      - "components/o-stepped-progress/main.js"
      - "components/o-stepped-progress/main.scss"
      - "components/o-stepped-progress/demos/**"
      - "components/o-stepped-progress/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
    - run: npm i -g npm@7
    - run: npm ci
    - run: node ./scripts/percy.js
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_STEPPED_PROGRESS }}
        WORKSPACE: components/o-stepped-progress
