name: percy components/o-labels
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}-components/o-labels
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: main
    paths:
      - "components/o-labels/package.json"
      - "components/o-labels/package-lock.json"
      - "components/o-labels/origami.json"
      - "components/o-labels/main.js"
      - "components/o-labels/main.scss"
      - "components/o-labels/demos/**"
      - "components/o-labels/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
    - run: npm ci
    - run: node ./scripts/percy.mjs
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_LABELS }}
        WORKSPACE: components/o-labels
