name: percy components/o-editorial-typography
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}-components/o-editorial-typography
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches: main
    paths:
      - "components/o-editorial-typography/package.json"
      - "components/o-editorial-typography/package-lock.json"
      - "components/o-editorial-typography/origami.json"
      - "components/o-editorial-typography/main.js"
      - "components/o-editorial-typography/main.scss"
      - "components/o-editorial-typography/demos/**"
      - "components/o-editorial-typography/src/**"

jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        cache: 'npm'
        node-version: 16
    - run: npm i -g npm@7
    - run: npm ci
    - run: node ./scripts/percy.js
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_COMPONENTS_O_EDITORIAL_TYPOGRAPHY }}
        WORKSPACE: components/o-editorial-typography
