name: percy
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    paths:
      - "package.json"
      - "package-lock.json"
      - "components/**"
      - "!components/**/*.md"
  push:
    branches: main
    paths:
      - "package.json"
      - "package-lock.json"
      - "components/**"
      - "!components/**/*.md"

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            components/ft-concept-button:
              - 'components/ft-concept-button/**'
            components/g-audio:
              - 'components/g-audio/**'
            components/n-notification:
              - 'components/n-notification/**'
            components/o-audio:
              - 'components/o-audio/**'
            components/o-autocomplete:
              - 'components/o-autocomplete/**'
            components/o-banner:
              - 'components/o-banner/**'
            components/o-big-number:
              - 'components/o-big-number/**'
            components/o-buttons:
              - 'components/o-buttons/**'
            components/o-colors:
              - 'components/o-colors/**'
            components/o-comments:
              - 'components/o-comments/**'
            components/o-cookie-message:
              - 'components/o-cookie-message/**'
            components/o-date:
              - 'components/o-date/**'
            components/o-editorial-layout:
              - 'components/o-editorial-layout/**'
            components/o-editorial-typography:
              - 'components/o-editorial-typography/**'
            components/o-expander:
              - 'components/o-expander/**'
            components/o-fonts:
              - 'components/o-fonts/**'
            components/o-footer:
              - 'components/o-footer/**'
            components/o-footer-services:
              - 'components/o-footer-services/**'
            components/o-forms:
              - 'components/o-forms/**'
            components/o-ft-affiliate-ribbon:
              - 'components/o-ft-affiliate-ribbon/**'
            components/o-grid:
              - 'components/o-grid/**'
            components/o-header:
              - 'components/o-header/**'
            components/o-header-services:
              - 'components/o-header-services/**'
            components/o-icons:
              - 'components/o-icons/**'
            components/o-labels:
              - 'components/o-labels/**'
            components/o-layout:
              - 'components/o-layout/**'
            components/o-lazy-load:
              - 'components/o-lazy-load/**'
            components/o-loading:
              - 'components/o-loading/**'
            components/o-message:
              - 'components/o-message/**'
            components/o-meter:
              - 'components/o-meter/**'
            components/o-multi-select:
              - 'components/o-multi-select/**'
            components/o-normalise:
              - 'components/o-normalise/**'
            components/o-overlay:
              - 'components/o-overlay/**'
            components/o-quote:
              - 'components/o-quote/**'
            components/o-share:
              - 'components/o-share/**'
            components/o-social-follow:
              - 'components/o-social-follow/**'
            components/o-spacing:
              - 'components/o-spacing/**'
            components/o-stepped-progress:
              - 'components/o-stepped-progress/**'
            components/o-subs-card:
              - 'components/o-subs-card/**'
            components/o-syntax-highlight:
              - 'components/o-syntax-highlight/**'
            components/o-table:
              - 'components/o-table/**'
            components/o-tabs:
              - 'components/o-tabs/**'
            components/o-teaser:
              - 'components/o-teaser/**'
            components/o-teaser-collection:
              - 'components/o-teaser-collection/**'
            components/o-toggle:
              - 'components/o-toggle/**'
            components/o-tooltip:
              - 'components/o-tooltip/**'
            components/o-top-banner:
              - 'components/o-top-banner/**'
            components/o-topper:
              - 'components/o-topper/**'
            components/o-typography:
              - 'components/o-typography/**'
            components/o-video:
              - 'components/o-video/**'
            components/o-viewport:
              - 'components/o-viewport/**'
            components/o-visual-effects:
              - 'components/o-visual-effects/**'
      - run: echo '${{ steps.filter.outputs.changes }}'
