name: percy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
#    paths:
#      - "package.json"
#      - "package-lock.json"
#      - "components/**"
#      - "!components/**/*.md"

jobs:
  percy-snapshotss:
    if: contains(github.event.pull_request.labels.*.name, 'percy')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace:
          - components/ft-concept-button
          - components/g-audio
        include:
          - workspace: components/ft-concept-button
            percyToken: PERCY_TOKEN_COMPONENTS_FT_CONCEPT_BUTTON
          - workspace: components/g-audio
            percyToken: PERCY_TOKEN_COMPONENTS_G_AUDIO
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          volta-version: "1.0.8"
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: node ./scripts/percy.js
        env:
          PERCY_TOKEN: ${{ secrets[matrix.percyToken] }}
          WORKSPACE: ${{ matrix.workspace }}
