name: test apps/storybook
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-apps/storybook
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i -g npm@7
    - run: npm ci
    - run: npx npm run -w apps/storybook lint
    - run: npx npm run -w apps/storybook test
