name: test components/o-footer-services
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-components/o-footer-services
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i -g npm@7
    - run: npm ci
    - run: npm run -w components&#x2F;o-footer-services lint --if-present
    - run: npm run -w components&#x2F;o-footer-services build --if-present
    - run: npm run -w components&#x2F;o-footer-services test --if-present
