name: test presets/eslint-config-origami-component
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-presets/eslint-config-origami-component
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i -g npm@7
    - run: npm ci
    - run: npm run -w presets/eslint-config-origami-component lint --if-present
    - run: npm run -w presets/eslint-config-origami-component build --if-present
    - run: npm run -w presets/eslint-config-origami-component test --if-present
