name: test tools/sass-linux-ia32
concurrency:
  group: ${{ github.head_ref }}-tools/sass-linux-ia32
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npx npm exec -w tools/sass-linux-ia32 -- origami-build-tools verify
    - run: npx npm run -w tools/sass-linux-ia32 test
