name: test apps/website
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-apps/website
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npx npm exec -w apps/website -- origami-build-tools verify
    - run: npx npm x -w apps/website -- origami-build-tools test || npx npm x -w apps/website -- origami-build-tools test
