name: test components/o-layout
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-components/o-layout
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i -g npm@7
    - run: npm ci
    - run: npx npm exec -w components/o-layout -- origami-build-tools verify
    - run: (npx npm x -w components/o-layout -- origami-build-tools test || npx npm x -w components/o-layout -- origami-build-tools test) && npx npm x -w components/o-layout -- a11y
