name: test tools/origami-build-tools
concurrency:
  group: ${{ github.head_ref }}-tools/origami-build-tools
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npx npm run -w tools/origami-build-tools lint
    - run: npx npm run -w tools/origami-build-tools test
