name: test apps/storybook/addons/html
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-apps/storybook/addons/html
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i -g npm@7
    - run: npm ci
    - run: npm run -w apps&#x2F;storybook&#x2F;addons&#x2F;html lint --if-present
    - run: npm run -w apps&#x2F;storybook&#x2F;addons&#x2F;html build --if-present
    - run: npm run -w apps&#x2F;storybook&#x2F;addons&#x2F;html test --if-present
