name: test components/o-labels
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-components/o-labels
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm run -w components/o-labels lint --if-present
    - run: npm run -w components/o-labels build --if-present
    - run: npm run -w components/o-labels test --if-present
