name: test presets/eslint-config-origami-component
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-presets/eslint-config-origami-component
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: xt0rted/stylelint-problem-matcher@v1
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm run -w presets/eslint-config-origami-component lint --if-present
    - run: npm run -w presets/eslint-config-origami-component build --if-present
    - run: npm run -w presets/eslint-config-origami-component test --if-present
