name: test tools/test-sass
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}-tools/test-sass
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm run -w tools/test-sass lint --if-present
    - run: npm run -w tools/test-sass build --if-present
    - run: npm run -w tools/test-sass test --if-present
