name: test
concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          components-ft-concept-button:
            - 'components/ft-concept-button/**'
          components-g-audio:
            - 'components/g-audio/**'
          components-n-notification:
            - 'components/n-notification/**'
          components-o-audio:
            - 'components/o-audio/**'
          components-o-autocomplete:
            - 'components/o-autocomplete/**'
          components-o-banner:
            - 'components/o-banner/**'
          components-o-big-number:
            - 'components/o-big-number/**'
          components-o-buttons:
            - 'components/o-buttons/**'
          components-o-colors:
            - 'components/o-colors/**'
          components-o-comments:
            - 'components/o-comments/**'
          components-o-cookie-message:
            - 'components/o-cookie-message/**'
          components-o-date:
            - 'components/o-date/**'
          components-o-editorial-layout:
            - 'components/o-editorial-layout/**'
          components-o-editorial-typography:
            - 'components/o-editorial-typography/**'
          components-o-expander:
            - 'components/o-expander/**'
          components-o-fonts:
            - 'components/o-fonts/**'
          components-o-footer:
            - 'components/o-footer/**'
          components-o-footer-services:
            - 'components/o-footer-services/**'
          components-o-forms:
            - 'components/o-forms/**'
          components-o-ft-affiliate-ribbon:
            - 'components/o-ft-affiliate-ribbon/**'
          components-o-grid:
            - 'components/o-grid/**'
          components-o-header:
            - 'components/o-header/**'
          components-o-header-services:
            - 'components/o-header-services/**'
          components-o-icons:
            - 'components/o-icons/**'
          components-o-labels:
            - 'components/o-labels/**'
          components-o-layout:
            - 'components/o-layout/**'
          components-o-lazy-load:
            - 'components/o-lazy-load/**'
          components-o-loading:
            - 'components/o-loading/**'
          components-o-message:
            - 'components/o-message/**'
          components-o-meter:
            - 'components/o-meter/**'
          components-o-multi-select:
            - 'components/o-multi-select/**'
          components-o-normalise:
            - 'components/o-normalise/**'
          components-o-overlay:
            - 'components/o-overlay/**'
          components-o-quote:
            - 'components/o-quote/**'
          components-o-share:
            - 'components/o-share/**'
          components-o-social-follow:
            - 'components/o-social-follow/**'
          components-o-spacing:
            - 'components/o-spacing/**'
          components-o-stepped-progress:
            - 'components/o-stepped-progress/**'
          components-o-subs-card:
            - 'components/o-subs-card/**'
          components-o-syntax-highlight:
            - 'components/o-syntax-highlight/**'
          components-o-table:
            - 'components/o-table/**'
          components-o-tabs:
            - 'components/o-tabs/**'
          components-o-teaser:
            - 'components/o-teaser/**'
          components-o-teaser-collection:
            - 'components/o-teaser-collection/**'
          components-o-toggle:
            - 'components/o-toggle/**'
          components-o-tooltip:
            - 'components/o-tooltip/**'
          components-o-top-banner:
            - 'components/o-top-banner/**'
          components-o-topper:
            - 'components/o-topper/**'
          components-o-typography:
            - 'components/o-typography/**'
          components-o-video:
            - 'components/o-video/**'
          components-o-viewport:
            - 'components/o-viewport/**'
          components-o-visual-effects:
            - 'components/o-visual-effects/**'
          libraries-ftdomdelegate:
            - 'libraries/ftdomdelegate/**'
          libraries-math:
            - 'libraries/math/**'
          libraries-o-autoinit:
            - 'libraries/o-autoinit/**'
          libraries-o-brand:
            - 'libraries/o-brand/**'
          libraries-o-errors:
            - 'libraries/o-errors/**'
          libraries-o-tracking:
            - 'libraries/o-tracking/**'
          libraries-o-utils:
            - 'libraries/o-utils/**'
          libraries-sass-mq:
            - 'libraries/sass-mq/**'
          presets-eslint-config-origami-component:
            - 'presets/eslint-config-origami-component/**'
          presets-remark-preset-lint-origami-component:
            - 'presets/remark-preset-lint-origami-component/**'
          presets-stylelint-config-origami-component:
            - 'presets/stylelint-config-origami-component/**'
          tools-a11y:
            - 'tools/a11y/**'
          tools-create-component:
            - 'tools/create-component/**'
          tools-demo-build:
            - 'tools/demo-build/**'
          tools-origami-bower-safe-version-supervisor:
            - 'tools/origami-bower-safe-version-supervisor/**'
          tools-origami-tools-helpers:
            - 'tools/origami-tools-helpers/**'
          tools-sass-compilation:
            - 'tools/sass-compilation/**'
          tools-test-javascript:
            - 'tools/test-javascript/**'
          tools-test-sass:
            - 'tools/test-sass/**'
          tools-validate-component-demo-html:
            - 'tools/validate-component-demo-html/**'
          tools-verify-origami-json:
            - 'tools/verify-origami-json/**'
          tools-verify-package-json:
            - 'tools/verify-package-json/**'
          apps-storybook-addons-background:
            - 'apps/storybook/addons/background/**'
          apps-storybook-addons-guidelines:
            - 'apps/storybook/addons/guidelines/**'
          apps-storybook-addons-html:
            - 'apps/storybook/addons/html/**'
          apps-storybook-addons-markdown-tabs:
            - 'apps/storybook/addons/markdown-tabs/**'
          apps-storybook:
            - 'apps/storybook/**'
          apps-website:
            - 'apps/website/**'
  test:
    if: ${{ needs.changes.outputs.components != '[]' && needs.changes.outputs.components != '' }}
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ${{ fromJson(needs.changes.outputs.components) }}
        include:
          - components-ft-concept-button:
            path: components/ft-concept-button
          - components-g-audio:
            path: components/g-audio
          - components-n-notification:
            path: components/n-notification
          - components-o-audio:
            path: components/o-audio
          - components-o-autocomplete:
            path: components/o-autocomplete
          - components-o-banner:
            path: components/o-banner
          - components-o-big-number:
            path: components/o-big-number
          - components-o-buttons:
            path: components/o-buttons
          - components-o-colors:
            path: components/o-colors
          - components-o-comments:
            path: components/o-comments
          - components-o-cookie-message:
            path: components/o-cookie-message
          - components-o-date:
            path: components/o-date
          - components-o-editorial-layout:
            path: components/o-editorial-layout
          - components-o-editorial-typography:
            path: components/o-editorial-typography
          - components-o-expander:
            path: components/o-expander
          - components-o-fonts:
            path: components/o-fonts
          - components-o-footer:
            path: components/o-footer
          - components-o-footer-services:
            path: components/o-footer-services
          - components-o-forms:
            path: components/o-forms
          - components-o-ft-affiliate-ribbon:
            path: components/o-ft-affiliate-ribbon
          - components-o-grid:
            path: components/o-grid
          - components-o-header:
            path: components/o-header
          - components-o-header-services:
            path: components/o-header-services
          - components-o-icons:
            path: components/o-icons
          - components-o-labels:
            path: components/o-labels
          - components-o-layout:
            path: components/o-layout
          - components-o-lazy-load:
            path: components/o-lazy-load
          - components-o-loading:
            path: components/o-loading
          - components-o-message:
            path: components/o-message
          - components-o-meter:
            path: components/o-meter
          - components-o-multi-select:
            path: components/o-multi-select
          - components-o-normalise:
            path: components/o-normalise
          - components-o-overlay:
            path: components/o-overlay
          - components-o-quote:
            path: components/o-quote
          - components-o-share:
            path: components/o-share
          - components-o-social-follow:
            path: components/o-social-follow
          - components-o-spacing:
            path: components/o-spacing
          - components-o-stepped-progress:
            path: components/o-stepped-progress
          - components-o-subs-card:
            path: components/o-subs-card
          - components-o-syntax-highlight:
            path: components/o-syntax-highlight
          - components-o-table:
            path: components/o-table
          - components-o-tabs:
            path: components/o-tabs
          - components-o-teaser:
            path: components/o-teaser
          - components-o-teaser-collection:
            path: components/o-teaser-collection
          - components-o-toggle:
            path: components/o-toggle
          - components-o-tooltip:
            path: components/o-tooltip
          - components-o-top-banner:
            path: components/o-top-banner
          - components-o-topper:
            path: components/o-topper
          - components-o-typography:
            path: components/o-typography
          - components-o-video:
            path: components/o-video
          - components-o-viewport:
            path: components/o-viewport
          - components-o-visual-effects:
            path: components/o-visual-effects
          - libraries-ftdomdelegate:
            path: libraries/ftdomdelegate
          - libraries-math:
            path: libraries/math
          - libraries-o-autoinit:
            path: libraries/o-autoinit
          - libraries-o-brand:
            path: libraries/o-brand
          - libraries-o-errors:
            path: libraries/o-errors
          - libraries-o-tracking:
            path: libraries/o-tracking
          - libraries-o-utils:
            path: libraries/o-utils
          - libraries-sass-mq:
            path: libraries/sass-mq
          - presets-eslint-config-origami-component:
            path: presets/eslint-config-origami-component
          - presets-remark-preset-lint-origami-component:
            path: presets/remark-preset-lint-origami-component
          - presets-stylelint-config-origami-component:
            path: presets/stylelint-config-origami-component
          - tools-a11y:
            path: tools/a11y
          - tools-create-component:
            path: tools/create-component
          - tools-demo-build:
            path: tools/demo-build
          - tools-origami-bower-safe-version-supervisor:
            path: tools/origami-bower-safe-version-supervisor
          - tools-origami-tools-helpers:
            path: tools/origami-tools-helpers
          - tools-sass-compilation:
            path: tools/sass-compilation
          - tools-test-javascript:
            path: tools/test-javascript
          - tools-test-sass:
            path: tools/test-sass
          - tools-validate-component-demo-html:
            path: tools/validate-component-demo-html
          - tools-verify-origami-json:
            path: tools/verify-origami-json
          - tools-verify-package-json:
            path: tools/verify-package-json
          - apps-storybook-addons-background:
            path: apps/storybook/addons/background
          - apps-storybook-addons-guidelines:
            path: apps/storybook/addons/guidelines
          - apps-storybook-addons-html:
            path: apps/storybook/addons/html
          - apps-storybook-addons-markdown-tabs:
            path: apps/storybook/addons/markdown-tabs
          - apps-storybook:
            path: apps/storybook
          - apps-website:
            path: apps/website
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          volta-version: "1.0.8"
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: echo "${{ toJson(matrix) }}"
      - run: npm ci
      - run: npm run -w ${{ matrix.path }} lint --if-present
      - run: npm run -w ${{ matrix.path }} build --if-present
      - run: npm run -w ${{ matrix.path }} test --if-present
