name: Test Origami Component
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install --only=dev
    - name: Repository name
      id: repo_name
      run: echo ::set-output name=REPO_NAME::$(echo $GITHUB_REPOSITORY | cut -d / -f 2)
    - run: npx origami-ci branch
      env:
        ORIGAMI_CI_NAME: ${{ steps.repo_name.outputs.REPO_NAME }}
        ORIGAMI_CI_VERSION: 0.0.0
