#!/bin/bash
set -e
# for a in `seq 1000`
# do
#  echo "echo $a && npm run test -w components/o-layout"
# done
echo 1 && npm run test -w components/o-layout
echo 2 && npm run test -w components/o-layout
echo 3 && npm run test -w components/o-layout
echo 4 && npm run test -w components/o-layout
echo 5 && npm run test -w components/o-layout
echo 6 && npm run test -w components/o-layout
echo 7 && npm run test -w components/o-layout
echo 8 && npm run test -w components/o-layout
echo 9 && npm run test -w components/o-layout
echo 10 && npm run test -w components/o-layout
echo 11 && npm run test -w components/o-layout
echo 12 && npm run test -w components/o-layout
echo 13 && npm run test -w components/o-layout
echo 14 && npm run test -w components/o-layout
echo 15 && npm run test -w components/o-layout
echo 16 && npm run test -w components/o-layout
echo 17 && npm run test -w components/o-layout
echo 18 && npm run test -w components/o-layout
echo 19 && npm run test -w components/o-layout
echo 20 && npm run test -w components/o-layout
echo 21 && npm run test -w components/o-layout
echo 22 && npm run test -w components/o-layout
echo 23 && npm run test -w components/o-layout
echo 24 && npm run test -w components/o-layout
echo 25 && npm run test -w components/o-layout
echo 26 && npm run test -w components/o-layout
echo 27 && npm run test -w components/o-layout
echo 28 && npm run test -w components/o-layout
echo 29 && npm run test -w components/o-layout
echo 30 && npm run test -w components/o-layout
echo 31 && npm run test -w components/o-layout
echo 32 && npm run test -w components/o-layout
echo 33 && npm run test -w components/o-layout
echo 34 && npm run test -w components/o-layout
echo 35 && npm run test -w components/o-layout
echo 36 && npm run test -w components/o-layout
echo 37 && npm run test -w components/o-layout
echo 38 && npm run test -w components/o-layout
echo 39 && npm run test -w components/o-layout
echo 40 && npm run test -w components/o-layout
echo 41 && npm run test -w components/o-layout
echo 42 && npm run test -w components/o-layout
echo 43 && npm run test -w components/o-layout
echo 44 && npm run test -w components/o-layout
echo 45 && npm run test -w components/o-layout
echo 46 && npm run test -w components/o-layout
echo 47 && npm run test -w components/o-layout
echo 48 && npm run test -w components/o-layout
echo 49 && npm run test -w components/o-layout
echo 50 && npm run test -w components/o-layout
echo 51 && npm run test -w components/o-layout
echo 52 && npm run test -w components/o-layout
echo 53 && npm run test -w components/o-layout
echo 54 && npm run test -w components/o-layout
echo 55 && npm run test -w components/o-layout
echo 56 && npm run test -w components/o-layout
echo 57 && npm run test -w components/o-layout
echo 58 && npm run test -w components/o-layout
echo 59 && npm run test -w components/o-layout
echo 60 && npm run test -w components/o-layout
echo 61 && npm run test -w components/o-layout
echo 62 && npm run test -w components/o-layout
echo 63 && npm run test -w components/o-layout
echo 64 && npm run test -w components/o-layout
echo 65 && npm run test -w components/o-layout
echo 66 && npm run test -w components/o-layout
echo 67 && npm run test -w components/o-layout
echo 68 && npm run test -w components/o-layout
echo 69 && npm run test -w components/o-layout
echo 70 && npm run test -w components/o-layout
echo 71 && npm run test -w components/o-layout
echo 72 && npm run test -w components/o-layout
echo 73 && npm run test -w components/o-layout
echo 74 && npm run test -w components/o-layout
echo 75 && npm run test -w components/o-layout
echo 76 && npm run test -w components/o-layout
echo 77 && npm run test -w components/o-layout
echo 78 && npm run test -w components/o-layout
echo 79 && npm run test -w components/o-layout
echo 80 && npm run test -w components/o-layout
echo 81 && npm run test -w components/o-layout
echo 82 && npm run test -w components/o-layout
echo 83 && npm run test -w components/o-layout
echo 84 && npm run test -w components/o-layout
echo 85 && npm run test -w components/o-layout
echo 86 && npm run test -w components/o-layout
echo 87 && npm run test -w components/o-layout
echo 88 && npm run test -w components/o-layout
echo 89 && npm run test -w components/o-layout
echo 90 && npm run test -w components/o-layout
echo 91 && npm run test -w components/o-layout
echo 92 && npm run test -w components/o-layout
echo 93 && npm run test -w components/o-layout
echo 94 && npm run test -w components/o-layout
echo 95 && npm run test -w components/o-layout
echo 96 && npm run test -w components/o-layout
echo 97 && npm run test -w components/o-layout
echo 98 && npm run test -w components/o-layout
echo 99 && npm run test -w components/o-layout
echo 100 && npm run test -w components/o-layout
echo 101 && npm run test -w components/o-layout
echo 102 && npm run test -w components/o-layout
echo 103 && npm run test -w components/o-layout
echo 104 && npm run test -w components/o-layout
echo 105 && npm run test -w components/o-layout
echo 106 && npm run test -w components/o-layout
echo 107 && npm run test -w components/o-layout
echo 108 && npm run test -w components/o-layout
echo 109 && npm run test -w components/o-layout
echo 110 && npm run test -w components/o-layout
echo 111 && npm run test -w components/o-layout
echo 112 && npm run test -w components/o-layout
echo 113 && npm run test -w components/o-layout
echo 114 && npm run test -w components/o-layout
echo 115 && npm run test -w components/o-layout
echo 116 && npm run test -w components/o-layout
echo 117 && npm run test -w components/o-layout
echo 118 && npm run test -w components/o-layout
echo 119 && npm run test -w components/o-layout
echo 120 && npm run test -w components/o-layout
echo 121 && npm run test -w components/o-layout
echo 122 && npm run test -w components/o-layout
echo 123 && npm run test -w components/o-layout
echo 124 && npm run test -w components/o-layout
echo 125 && npm run test -w components/o-layout
echo 126 && npm run test -w components/o-layout
echo 127 && npm run test -w components/o-layout
echo 128 && npm run test -w components/o-layout
echo 129 && npm run test -w components/o-layout
echo 130 && npm run test -w components/o-layout
echo 131 && npm run test -w components/o-layout
echo 132 && npm run test -w components/o-layout
echo 133 && npm run test -w components/o-layout
echo 134 && npm run test -w components/o-layout
echo 135 && npm run test -w components/o-layout
echo 136 && npm run test -w components/o-layout
echo 137 && npm run test -w components/o-layout
echo 138 && npm run test -w components/o-layout
echo 139 && npm run test -w components/o-layout
echo 140 && npm run test -w components/o-layout
echo 141 && npm run test -w components/o-layout
echo 142 && npm run test -w components/o-layout
echo 143 && npm run test -w components/o-layout
echo 144 && npm run test -w components/o-layout
echo 145 && npm run test -w components/o-layout
echo 146 && npm run test -w components/o-layout
echo 147 && npm run test -w components/o-layout
echo 148 && npm run test -w components/o-layout
echo 149 && npm run test -w components/o-layout
echo 150 && npm run test -w components/o-layout
echo 151 && npm run test -w components/o-layout
echo 152 && npm run test -w components/o-layout
echo 153 && npm run test -w components/o-layout
echo 154 && npm run test -w components/o-layout
echo 155 && npm run test -w components/o-layout
echo 156 && npm run test -w components/o-layout
echo 157 && npm run test -w components/o-layout
echo 158 && npm run test -w components/o-layout
echo 159 && npm run test -w components/o-layout
echo 160 && npm run test -w components/o-layout
echo 161 && npm run test -w components/o-layout
echo 162 && npm run test -w components/o-layout
echo 163 && npm run test -w components/o-layout
echo 164 && npm run test -w components/o-layout
echo 165 && npm run test -w components/o-layout
echo 166 && npm run test -w components/o-layout
echo 167 && npm run test -w components/o-layout
echo 168 && npm run test -w components/o-layout
echo 169 && npm run test -w components/o-layout
echo 170 && npm run test -w components/o-layout
echo 171 && npm run test -w components/o-layout
echo 172 && npm run test -w components/o-layout
echo 173 && npm run test -w components/o-layout
echo 174 && npm run test -w components/o-layout
echo 175 && npm run test -w components/o-layout
echo 176 && npm run test -w components/o-layout
echo 177 && npm run test -w components/o-layout
echo 178 && npm run test -w components/o-layout
echo 179 && npm run test -w components/o-layout
echo 180 && npm run test -w components/o-layout
echo 181 && npm run test -w components/o-layout
echo 182 && npm run test -w components/o-layout
echo 183 && npm run test -w components/o-layout
echo 184 && npm run test -w components/o-layout
echo 185 && npm run test -w components/o-layout
echo 186 && npm run test -w components/o-layout
echo 187 && npm run test -w components/o-layout
echo 188 && npm run test -w components/o-layout
echo 189 && npm run test -w components/o-layout
echo 190 && npm run test -w components/o-layout
echo 191 && npm run test -w components/o-layout
echo 192 && npm run test -w components/o-layout
echo 193 && npm run test -w components/o-layout
echo 194 && npm run test -w components/o-layout
echo 195 && npm run test -w components/o-layout
echo 196 && npm run test -w components/o-layout
echo 197 && npm run test -w components/o-layout
echo 198 && npm run test -w components/o-layout
echo 199 && npm run test -w components/o-layout
echo 200 && npm run test -w components/o-layout
echo 201 && npm run test -w components/o-layout
echo 202 && npm run test -w components/o-layout
echo 203 && npm run test -w components/o-layout
echo 204 && npm run test -w components/o-layout
echo 205 && npm run test -w components/o-layout
echo 206 && npm run test -w components/o-layout
echo 207 && npm run test -w components/o-layout
echo 208 && npm run test -w components/o-layout
echo 209 && npm run test -w components/o-layout
echo 210 && npm run test -w components/o-layout
echo 211 && npm run test -w components/o-layout
echo 212 && npm run test -w components/o-layout
echo 213 && npm run test -w components/o-layout
echo 214 && npm run test -w components/o-layout
echo 215 && npm run test -w components/o-layout
echo 216 && npm run test -w components/o-layout
echo 217 && npm run test -w components/o-layout
echo 218 && npm run test -w components/o-layout
echo 219 && npm run test -w components/o-layout
echo 220 && npm run test -w components/o-layout
echo 221 && npm run test -w components/o-layout
echo 222 && npm run test -w components/o-layout
echo 223 && npm run test -w components/o-layout
echo 224 && npm run test -w components/o-layout
echo 225 && npm run test -w components/o-layout
echo 226 && npm run test -w components/o-layout
echo 227 && npm run test -w components/o-layout
echo 228 && npm run test -w components/o-layout
echo 229 && npm run test -w components/o-layout
echo 230 && npm run test -w components/o-layout
echo 231 && npm run test -w components/o-layout
echo 232 && npm run test -w components/o-layout
echo 233 && npm run test -w components/o-layout
echo 234 && npm run test -w components/o-layout
echo 235 && npm run test -w components/o-layout
echo 236 && npm run test -w components/o-layout
echo 237 && npm run test -w components/o-layout
echo 238 && npm run test -w components/o-layout
echo 239 && npm run test -w components/o-layout
echo 240 && npm run test -w components/o-layout
echo 241 && npm run test -w components/o-layout
echo 242 && npm run test -w components/o-layout
echo 243 && npm run test -w components/o-layout
echo 244 && npm run test -w components/o-layout
echo 245 && npm run test -w components/o-layout
echo 246 && npm run test -w components/o-layout
echo 247 && npm run test -w components/o-layout
echo 248 && npm run test -w components/o-layout
echo 249 && npm run test -w components/o-layout
echo 250 && npm run test -w components/o-layout
echo 251 && npm run test -w components/o-layout
echo 252 && npm run test -w components/o-layout
echo 253 && npm run test -w components/o-layout
echo 254 && npm run test -w components/o-layout
echo 255 && npm run test -w components/o-layout
echo 256 && npm run test -w components/o-layout
echo 257 && npm run test -w components/o-layout
echo 258 && npm run test -w components/o-layout
echo 259 && npm run test -w components/o-layout
echo 260 && npm run test -w components/o-layout
echo 261 && npm run test -w components/o-layout
echo 262 && npm run test -w components/o-layout
echo 263 && npm run test -w components/o-layout
echo 264 && npm run test -w components/o-layout
echo 265 && npm run test -w components/o-layout
echo 266 && npm run test -w components/o-layout
echo 267 && npm run test -w components/o-layout
echo 268 && npm run test -w components/o-layout
echo 269 && npm run test -w components/o-layout
echo 270 && npm run test -w components/o-layout
echo 271 && npm run test -w components/o-layout
echo 272 && npm run test -w components/o-layout
echo 273 && npm run test -w components/o-layout
echo 274 && npm run test -w components/o-layout
echo 275 && npm run test -w components/o-layout
echo 276 && npm run test -w components/o-layout
echo 277 && npm run test -w components/o-layout
echo 278 && npm run test -w components/o-layout
echo 279 && npm run test -w components/o-layout
echo 280 && npm run test -w components/o-layout
echo 281 && npm run test -w components/o-layout
echo 282 && npm run test -w components/o-layout
echo 283 && npm run test -w components/o-layout
echo 284 && npm run test -w components/o-layout
echo 285 && npm run test -w components/o-layout
echo 286 && npm run test -w components/o-layout
echo 287 && npm run test -w components/o-layout
echo 288 && npm run test -w components/o-layout
echo 289 && npm run test -w components/o-layout
echo 290 && npm run test -w components/o-layout
echo 291 && npm run test -w components/o-layout
echo 292 && npm run test -w components/o-layout
echo 293 && npm run test -w components/o-layout
echo 294 && npm run test -w components/o-layout
echo 295 && npm run test -w components/o-layout
echo 296 && npm run test -w components/o-layout
echo 297 && npm run test -w components/o-layout
echo 298 && npm run test -w components/o-layout
echo 299 && npm run test -w components/o-layout
echo 300 && npm run test -w components/o-layout
echo 301 && npm run test -w components/o-layout
echo 302 && npm run test -w components/o-layout
echo 303 && npm run test -w components/o-layout
echo 304 && npm run test -w components/o-layout
echo 305 && npm run test -w components/o-layout
echo 306 && npm run test -w components/o-layout
echo 307 && npm run test -w components/o-layout
echo 308 && npm run test -w components/o-layout
echo 309 && npm run test -w components/o-layout
echo 310 && npm run test -w components/o-layout
echo 311 && npm run test -w components/o-layout
echo 312 && npm run test -w components/o-layout
echo 313 && npm run test -w components/o-layout
echo 314 && npm run test -w components/o-layout
echo 315 && npm run test -w components/o-layout
echo 316 && npm run test -w components/o-layout
echo 317 && npm run test -w components/o-layout
echo 318 && npm run test -w components/o-layout
echo 319 && npm run test -w components/o-layout
echo 320 && npm run test -w components/o-layout
echo 321 && npm run test -w components/o-layout
echo 322 && npm run test -w components/o-layout
echo 323 && npm run test -w components/o-layout
echo 324 && npm run test -w components/o-layout
echo 325 && npm run test -w components/o-layout
echo 326 && npm run test -w components/o-layout
echo 327 && npm run test -w components/o-layout
echo 328 && npm run test -w components/o-layout
echo 329 && npm run test -w components/o-layout
echo 330 && npm run test -w components/o-layout
echo 331 && npm run test -w components/o-layout
echo 332 && npm run test -w components/o-layout
echo 333 && npm run test -w components/o-layout
echo 334 && npm run test -w components/o-layout
echo 335 && npm run test -w components/o-layout
echo 336 && npm run test -w components/o-layout
echo 337 && npm run test -w components/o-layout
echo 338 && npm run test -w components/o-layout
echo 339 && npm run test -w components/o-layout
echo 340 && npm run test -w components/o-layout
echo 341 && npm run test -w components/o-layout
echo 342 && npm run test -w components/o-layout
echo 343 && npm run test -w components/o-layout
echo 344 && npm run test -w components/o-layout
echo 345 && npm run test -w components/o-layout
echo 346 && npm run test -w components/o-layout
echo 347 && npm run test -w components/o-layout
echo 348 && npm run test -w components/o-layout
echo 349 && npm run test -w components/o-layout
echo 350 && npm run test -w components/o-layout
echo 351 && npm run test -w components/o-layout
echo 352 && npm run test -w components/o-layout
echo 353 && npm run test -w components/o-layout
echo 354 && npm run test -w components/o-layout
echo 355 && npm run test -w components/o-layout
echo 356 && npm run test -w components/o-layout
echo 357 && npm run test -w components/o-layout
echo 358 && npm run test -w components/o-layout
echo 359 && npm run test -w components/o-layout
echo 360 && npm run test -w components/o-layout
echo 361 && npm run test -w components/o-layout
echo 362 && npm run test -w components/o-layout
echo 363 && npm run test -w components/o-layout
echo 364 && npm run test -w components/o-layout
echo 365 && npm run test -w components/o-layout
echo 366 && npm run test -w components/o-layout
echo 367 && npm run test -w components/o-layout
echo 368 && npm run test -w components/o-layout
echo 369 && npm run test -w components/o-layout
echo 370 && npm run test -w components/o-layout
echo 371 && npm run test -w components/o-layout
echo 372 && npm run test -w components/o-layout
echo 373 && npm run test -w components/o-layout
echo 374 && npm run test -w components/o-layout
echo 375 && npm run test -w components/o-layout
echo 376 && npm run test -w components/o-layout
echo 377 && npm run test -w components/o-layout
echo 378 && npm run test -w components/o-layout
echo 379 && npm run test -w components/o-layout
echo 380 && npm run test -w components/o-layout
echo 381 && npm run test -w components/o-layout
echo 382 && npm run test -w components/o-layout
echo 383 && npm run test -w components/o-layout
echo 384 && npm run test -w components/o-layout
echo 385 && npm run test -w components/o-layout
echo 386 && npm run test -w components/o-layout
echo 387 && npm run test -w components/o-layout
echo 388 && npm run test -w components/o-layout
echo 389 && npm run test -w components/o-layout
echo 390 && npm run test -w components/o-layout
echo 391 && npm run test -w components/o-layout
echo 392 && npm run test -w components/o-layout
echo 393 && npm run test -w components/o-layout
echo 394 && npm run test -w components/o-layout
echo 395 && npm run test -w components/o-layout
echo 396 && npm run test -w components/o-layout
echo 397 && npm run test -w components/o-layout
echo 398 && npm run test -w components/o-layout
echo 399 && npm run test -w components/o-layout
echo 400 && npm run test -w components/o-layout
echo 401 && npm run test -w components/o-layout
echo 402 && npm run test -w components/o-layout
echo 403 && npm run test -w components/o-layout
echo 404 && npm run test -w components/o-layout
echo 405 && npm run test -w components/o-layout
echo 406 && npm run test -w components/o-layout
echo 407 && npm run test -w components/o-layout
echo 408 && npm run test -w components/o-layout
echo 409 && npm run test -w components/o-layout
echo 410 && npm run test -w components/o-layout
echo 411 && npm run test -w components/o-layout
echo 412 && npm run test -w components/o-layout
echo 413 && npm run test -w components/o-layout
echo 414 && npm run test -w components/o-layout
echo 415 && npm run test -w components/o-layout
echo 416 && npm run test -w components/o-layout
echo 417 && npm run test -w components/o-layout
echo 418 && npm run test -w components/o-layout
echo 419 && npm run test -w components/o-layout
echo 420 && npm run test -w components/o-layout
echo 421 && npm run test -w components/o-layout
echo 422 && npm run test -w components/o-layout
echo 423 && npm run test -w components/o-layout
echo 424 && npm run test -w components/o-layout
echo 425 && npm run test -w components/o-layout
echo 426 && npm run test -w components/o-layout
echo 427 && npm run test -w components/o-layout
echo 428 && npm run test -w components/o-layout
echo 429 && npm run test -w components/o-layout
echo 430 && npm run test -w components/o-layout
echo 431 && npm run test -w components/o-layout
echo 432 && npm run test -w components/o-layout
echo 433 && npm run test -w components/o-layout
echo 434 && npm run test -w components/o-layout
echo 435 && npm run test -w components/o-layout
echo 436 && npm run test -w components/o-layout
echo 437 && npm run test -w components/o-layout
echo 438 && npm run test -w components/o-layout
echo 439 && npm run test -w components/o-layout
echo 440 && npm run test -w components/o-layout
echo 441 && npm run test -w components/o-layout
echo 442 && npm run test -w components/o-layout
echo 443 && npm run test -w components/o-layout
echo 444 && npm run test -w components/o-layout
echo 445 && npm run test -w components/o-layout
echo 446 && npm run test -w components/o-layout
echo 447 && npm run test -w components/o-layout
echo 448 && npm run test -w components/o-layout
echo 449 && npm run test -w components/o-layout
echo 450 && npm run test -w components/o-layout
echo 451 && npm run test -w components/o-layout
echo 452 && npm run test -w components/o-layout
echo 453 && npm run test -w components/o-layout
echo 454 && npm run test -w components/o-layout
echo 455 && npm run test -w components/o-layout
echo 456 && npm run test -w components/o-layout
echo 457 && npm run test -w components/o-layout
echo 458 && npm run test -w components/o-layout
echo 459 && npm run test -w components/o-layout
echo 460 && npm run test -w components/o-layout
echo 461 && npm run test -w components/o-layout
echo 462 && npm run test -w components/o-layout
echo 463 && npm run test -w components/o-layout
echo 464 && npm run test -w components/o-layout
echo 465 && npm run test -w components/o-layout
echo 466 && npm run test -w components/o-layout
echo 467 && npm run test -w components/o-layout
echo 468 && npm run test -w components/o-layout
echo 469 && npm run test -w components/o-layout
echo 470 && npm run test -w components/o-layout
echo 471 && npm run test -w components/o-layout
echo 472 && npm run test -w components/o-layout
echo 473 && npm run test -w components/o-layout
echo 474 && npm run test -w components/o-layout
echo 475 && npm run test -w components/o-layout
echo 476 && npm run test -w components/o-layout
echo 477 && npm run test -w components/o-layout
echo 478 && npm run test -w components/o-layout
echo 479 && npm run test -w components/o-layout
echo 480 && npm run test -w components/o-layout
echo 481 && npm run test -w components/o-layout
echo 482 && npm run test -w components/o-layout
echo 483 && npm run test -w components/o-layout
echo 484 && npm run test -w components/o-layout
echo 485 && npm run test -w components/o-layout
echo 486 && npm run test -w components/o-layout
echo 487 && npm run test -w components/o-layout
echo 488 && npm run test -w components/o-layout
echo 489 && npm run test -w components/o-layout
echo 490 && npm run test -w components/o-layout
echo 491 && npm run test -w components/o-layout
echo 492 && npm run test -w components/o-layout
echo 493 && npm run test -w components/o-layout
echo 494 && npm run test -w components/o-layout
echo 495 && npm run test -w components/o-layout
echo 496 && npm run test -w components/o-layout
echo 497 && npm run test -w components/o-layout
echo 498 && npm run test -w components/o-layout
echo 499 && npm run test -w components/o-layout
echo 500 && npm run test -w components/o-layout
echo 501 && npm run test -w components/o-layout
echo 502 && npm run test -w components/o-layout
echo 503 && npm run test -w components/o-layout
echo 504 && npm run test -w components/o-layout
echo 505 && npm run test -w components/o-layout
echo 506 && npm run test -w components/o-layout
echo 507 && npm run test -w components/o-layout
echo 508 && npm run test -w components/o-layout
echo 509 && npm run test -w components/o-layout
echo 510 && npm run test -w components/o-layout
echo 511 && npm run test -w components/o-layout
echo 512 && npm run test -w components/o-layout
echo 513 && npm run test -w components/o-layout
echo 514 && npm run test -w components/o-layout
echo 515 && npm run test -w components/o-layout
echo 516 && npm run test -w components/o-layout
echo 517 && npm run test -w components/o-layout
echo 518 && npm run test -w components/o-layout
echo 519 && npm run test -w components/o-layout
echo 520 && npm run test -w components/o-layout
echo 521 && npm run test -w components/o-layout
echo 522 && npm run test -w components/o-layout
echo 523 && npm run test -w components/o-layout
echo 524 && npm run test -w components/o-layout
echo 525 && npm run test -w components/o-layout
echo 526 && npm run test -w components/o-layout
echo 527 && npm run test -w components/o-layout
echo 528 && npm run test -w components/o-layout
echo 529 && npm run test -w components/o-layout
echo 530 && npm run test -w components/o-layout
echo 531 && npm run test -w components/o-layout
echo 532 && npm run test -w components/o-layout
echo 533 && npm run test -w components/o-layout
echo 534 && npm run test -w components/o-layout
echo 535 && npm run test -w components/o-layout
echo 536 && npm run test -w components/o-layout
echo 537 && npm run test -w components/o-layout
echo 538 && npm run test -w components/o-layout
echo 539 && npm run test -w components/o-layout
echo 540 && npm run test -w components/o-layout
echo 541 && npm run test -w components/o-layout
echo 542 && npm run test -w components/o-layout
echo 543 && npm run test -w components/o-layout
echo 544 && npm run test -w components/o-layout
echo 545 && npm run test -w components/o-layout
echo 546 && npm run test -w components/o-layout
echo 547 && npm run test -w components/o-layout
echo 548 && npm run test -w components/o-layout
echo 549 && npm run test -w components/o-layout
echo 550 && npm run test -w components/o-layout
echo 551 && npm run test -w components/o-layout
echo 552 && npm run test -w components/o-layout
echo 553 && npm run test -w components/o-layout
echo 554 && npm run test -w components/o-layout
echo 555 && npm run test -w components/o-layout
echo 556 && npm run test -w components/o-layout
echo 557 && npm run test -w components/o-layout
echo 558 && npm run test -w components/o-layout
echo 559 && npm run test -w components/o-layout
echo 560 && npm run test -w components/o-layout
echo 561 && npm run test -w components/o-layout
echo 562 && npm run test -w components/o-layout
echo 563 && npm run test -w components/o-layout
echo 564 && npm run test -w components/o-layout
echo 565 && npm run test -w components/o-layout
echo 566 && npm run test -w components/o-layout
echo 567 && npm run test -w components/o-layout
echo 568 && npm run test -w components/o-layout
echo 569 && npm run test -w components/o-layout
echo 570 && npm run test -w components/o-layout
echo 571 && npm run test -w components/o-layout
echo 572 && npm run test -w components/o-layout
echo 573 && npm run test -w components/o-layout
echo 574 && npm run test -w components/o-layout
echo 575 && npm run test -w components/o-layout
echo 576 && npm run test -w components/o-layout
echo 577 && npm run test -w components/o-layout
echo 578 && npm run test -w components/o-layout
echo 579 && npm run test -w components/o-layout
echo 580 && npm run test -w components/o-layout
echo 581 && npm run test -w components/o-layout
echo 582 && npm run test -w components/o-layout
echo 583 && npm run test -w components/o-layout
echo 584 && npm run test -w components/o-layout
echo 585 && npm run test -w components/o-layout
echo 586 && npm run test -w components/o-layout
echo 587 && npm run test -w components/o-layout
echo 588 && npm run test -w components/o-layout
echo 589 && npm run test -w components/o-layout
echo 590 && npm run test -w components/o-layout
echo 591 && npm run test -w components/o-layout
echo 592 && npm run test -w components/o-layout
echo 593 && npm run test -w components/o-layout
echo 594 && npm run test -w components/o-layout
echo 595 && npm run test -w components/o-layout
echo 596 && npm run test -w components/o-layout
echo 597 && npm run test -w components/o-layout
echo 598 && npm run test -w components/o-layout
echo 599 && npm run test -w components/o-layout
echo 600 && npm run test -w components/o-layout
echo 601 && npm run test -w components/o-layout
echo 602 && npm run test -w components/o-layout
echo 603 && npm run test -w components/o-layout
echo 604 && npm run test -w components/o-layout
echo 605 && npm run test -w components/o-layout
echo 606 && npm run test -w components/o-layout
echo 607 && npm run test -w components/o-layout
echo 608 && npm run test -w components/o-layout
echo 609 && npm run test -w components/o-layout
echo 610 && npm run test -w components/o-layout
echo 611 && npm run test -w components/o-layout
echo 612 && npm run test -w components/o-layout
echo 613 && npm run test -w components/o-layout
echo 614 && npm run test -w components/o-layout
echo 615 && npm run test -w components/o-layout
echo 616 && npm run test -w components/o-layout
echo 617 && npm run test -w components/o-layout
echo 618 && npm run test -w components/o-layout
echo 619 && npm run test -w components/o-layout
echo 620 && npm run test -w components/o-layout
echo 621 && npm run test -w components/o-layout
echo 622 && npm run test -w components/o-layout
echo 623 && npm run test -w components/o-layout
echo 624 && npm run test -w components/o-layout
echo 625 && npm run test -w components/o-layout
echo 626 && npm run test -w components/o-layout
echo 627 && npm run test -w components/o-layout
echo 628 && npm run test -w components/o-layout
echo 629 && npm run test -w components/o-layout
echo 630 && npm run test -w components/o-layout
echo 631 && npm run test -w components/o-layout
echo 632 && npm run test -w components/o-layout
echo 633 && npm run test -w components/o-layout
echo 634 && npm run test -w components/o-layout
echo 635 && npm run test -w components/o-layout
echo 636 && npm run test -w components/o-layout
echo 637 && npm run test -w components/o-layout
echo 638 && npm run test -w components/o-layout
echo 639 && npm run test -w components/o-layout
echo 640 && npm run test -w components/o-layout
echo 641 && npm run test -w components/o-layout
echo 642 && npm run test -w components/o-layout
echo 643 && npm run test -w components/o-layout
echo 644 && npm run test -w components/o-layout
echo 645 && npm run test -w components/o-layout
echo 646 && npm run test -w components/o-layout
echo 647 && npm run test -w components/o-layout
echo 648 && npm run test -w components/o-layout
echo 649 && npm run test -w components/o-layout
echo 650 && npm run test -w components/o-layout
echo 651 && npm run test -w components/o-layout
echo 652 && npm run test -w components/o-layout
echo 653 && npm run test -w components/o-layout
echo 654 && npm run test -w components/o-layout
echo 655 && npm run test -w components/o-layout
echo 656 && npm run test -w components/o-layout
echo 657 && npm run test -w components/o-layout
echo 658 && npm run test -w components/o-layout
echo 659 && npm run test -w components/o-layout
echo 660 && npm run test -w components/o-layout
echo 661 && npm run test -w components/o-layout
echo 662 && npm run test -w components/o-layout
echo 663 && npm run test -w components/o-layout
echo 664 && npm run test -w components/o-layout
echo 665 && npm run test -w components/o-layout
echo 666 && npm run test -w components/o-layout
echo 667 && npm run test -w components/o-layout
echo 668 && npm run test -w components/o-layout
echo 669 && npm run test -w components/o-layout
echo 670 && npm run test -w components/o-layout
echo 671 && npm run test -w components/o-layout
echo 672 && npm run test -w components/o-layout
echo 673 && npm run test -w components/o-layout
echo 674 && npm run test -w components/o-layout
echo 675 && npm run test -w components/o-layout
echo 676 && npm run test -w components/o-layout
echo 677 && npm run test -w components/o-layout
echo 678 && npm run test -w components/o-layout
echo 679 && npm run test -w components/o-layout
echo 680 && npm run test -w components/o-layout
echo 681 && npm run test -w components/o-layout
echo 682 && npm run test -w components/o-layout
echo 683 && npm run test -w components/o-layout
echo 684 && npm run test -w components/o-layout
echo 685 && npm run test -w components/o-layout
echo 686 && npm run test -w components/o-layout
echo 687 && npm run test -w components/o-layout
echo 688 && npm run test -w components/o-layout
echo 689 && npm run test -w components/o-layout
echo 690 && npm run test -w components/o-layout
echo 691 && npm run test -w components/o-layout
echo 692 && npm run test -w components/o-layout
echo 693 && npm run test -w components/o-layout
echo 694 && npm run test -w components/o-layout
echo 695 && npm run test -w components/o-layout
echo 696 && npm run test -w components/o-layout
echo 697 && npm run test -w components/o-layout
echo 698 && npm run test -w components/o-layout
echo 699 && npm run test -w components/o-layout
echo 700 && npm run test -w components/o-layout
echo 701 && npm run test -w components/o-layout
echo 702 && npm run test -w components/o-layout
echo 703 && npm run test -w components/o-layout
echo 704 && npm run test -w components/o-layout
echo 705 && npm run test -w components/o-layout
echo 706 && npm run test -w components/o-layout
echo 707 && npm run test -w components/o-layout
echo 708 && npm run test -w components/o-layout
echo 709 && npm run test -w components/o-layout
echo 710 && npm run test -w components/o-layout
echo 711 && npm run test -w components/o-layout
echo 712 && npm run test -w components/o-layout
echo 713 && npm run test -w components/o-layout
echo 714 && npm run test -w components/o-layout
echo 715 && npm run test -w components/o-layout
echo 716 && npm run test -w components/o-layout
echo 717 && npm run test -w components/o-layout
echo 718 && npm run test -w components/o-layout
echo 719 && npm run test -w components/o-layout
echo 720 && npm run test -w components/o-layout
echo 721 && npm run test -w components/o-layout
echo 722 && npm run test -w components/o-layout
echo 723 && npm run test -w components/o-layout
echo 724 && npm run test -w components/o-layout
echo 725 && npm run test -w components/o-layout
echo 726 && npm run test -w components/o-layout
echo 727 && npm run test -w components/o-layout
echo 728 && npm run test -w components/o-layout
echo 729 && npm run test -w components/o-layout
echo 730 && npm run test -w components/o-layout
echo 731 && npm run test -w components/o-layout
echo 732 && npm run test -w components/o-layout
echo 733 && npm run test -w components/o-layout
echo 734 && npm run test -w components/o-layout
echo 735 && npm run test -w components/o-layout
echo 736 && npm run test -w components/o-layout
echo 737 && npm run test -w components/o-layout
echo 738 && npm run test -w components/o-layout
echo 739 && npm run test -w components/o-layout
echo 740 && npm run test -w components/o-layout
echo 741 && npm run test -w components/o-layout
echo 742 && npm run test -w components/o-layout
echo 743 && npm run test -w components/o-layout
echo 744 && npm run test -w components/o-layout
echo 745 && npm run test -w components/o-layout
echo 746 && npm run test -w components/o-layout
echo 747 && npm run test -w components/o-layout
echo 748 && npm run test -w components/o-layout
echo 749 && npm run test -w components/o-layout
echo 750 && npm run test -w components/o-layout
echo 751 && npm run test -w components/o-layout
echo 752 && npm run test -w components/o-layout
echo 753 && npm run test -w components/o-layout
echo 754 && npm run test -w components/o-layout
echo 755 && npm run test -w components/o-layout
echo 756 && npm run test -w components/o-layout
echo 757 && npm run test -w components/o-layout
echo 758 && npm run test -w components/o-layout
echo 759 && npm run test -w components/o-layout
echo 760 && npm run test -w components/o-layout
echo 761 && npm run test -w components/o-layout
echo 762 && npm run test -w components/o-layout
echo 763 && npm run test -w components/o-layout
echo 764 && npm run test -w components/o-layout
echo 765 && npm run test -w components/o-layout
echo 766 && npm run test -w components/o-layout
echo 767 && npm run test -w components/o-layout
echo 768 && npm run test -w components/o-layout
echo 769 && npm run test -w components/o-layout
echo 770 && npm run test -w components/o-layout
echo 771 && npm run test -w components/o-layout
echo 772 && npm run test -w components/o-layout
echo 773 && npm run test -w components/o-layout
echo 774 && npm run test -w components/o-layout
echo 775 && npm run test -w components/o-layout
echo 776 && npm run test -w components/o-layout
echo 777 && npm run test -w components/o-layout
echo 778 && npm run test -w components/o-layout
echo 779 && npm run test -w components/o-layout
echo 780 && npm run test -w components/o-layout
echo 781 && npm run test -w components/o-layout
echo 782 && npm run test -w components/o-layout
echo 783 && npm run test -w components/o-layout
echo 784 && npm run test -w components/o-layout
echo 785 && npm run test -w components/o-layout
echo 786 && npm run test -w components/o-layout
echo 787 && npm run test -w components/o-layout
echo 788 && npm run test -w components/o-layout
echo 789 && npm run test -w components/o-layout
echo 790 && npm run test -w components/o-layout
echo 791 && npm run test -w components/o-layout
echo 792 && npm run test -w components/o-layout
echo 793 && npm run test -w components/o-layout
echo 794 && npm run test -w components/o-layout
echo 795 && npm run test -w components/o-layout
echo 796 && npm run test -w components/o-layout
echo 797 && npm run test -w components/o-layout
echo 798 && npm run test -w components/o-layout
echo 799 && npm run test -w components/o-layout
echo 800 && npm run test -w components/o-layout
echo 801 && npm run test -w components/o-layout
echo 802 && npm run test -w components/o-layout
echo 803 && npm run test -w components/o-layout
echo 804 && npm run test -w components/o-layout
echo 805 && npm run test -w components/o-layout
echo 806 && npm run test -w components/o-layout
echo 807 && npm run test -w components/o-layout
echo 808 && npm run test -w components/o-layout
echo 809 && npm run test -w components/o-layout
echo 810 && npm run test -w components/o-layout
echo 811 && npm run test -w components/o-layout
echo 812 && npm run test -w components/o-layout
echo 813 && npm run test -w components/o-layout
echo 814 && npm run test -w components/o-layout
echo 815 && npm run test -w components/o-layout
echo 816 && npm run test -w components/o-layout
echo 817 && npm run test -w components/o-layout
echo 818 && npm run test -w components/o-layout
echo 819 && npm run test -w components/o-layout
echo 820 && npm run test -w components/o-layout
echo 821 && npm run test -w components/o-layout
echo 822 && npm run test -w components/o-layout
echo 823 && npm run test -w components/o-layout
echo 824 && npm run test -w components/o-layout
echo 825 && npm run test -w components/o-layout
echo 826 && npm run test -w components/o-layout
echo 827 && npm run test -w components/o-layout
echo 828 && npm run test -w components/o-layout
echo 829 && npm run test -w components/o-layout
echo 830 && npm run test -w components/o-layout
echo 831 && npm run test -w components/o-layout
echo 832 && npm run test -w components/o-layout
echo 833 && npm run test -w components/o-layout
echo 834 && npm run test -w components/o-layout
echo 835 && npm run test -w components/o-layout
echo 836 && npm run test -w components/o-layout
echo 837 && npm run test -w components/o-layout
echo 838 && npm run test -w components/o-layout
echo 839 && npm run test -w components/o-layout
echo 840 && npm run test -w components/o-layout
echo 841 && npm run test -w components/o-layout
echo 842 && npm run test -w components/o-layout
echo 843 && npm run test -w components/o-layout
echo 844 && npm run test -w components/o-layout
echo 845 && npm run test -w components/o-layout
echo 846 && npm run test -w components/o-layout
echo 847 && npm run test -w components/o-layout
echo 848 && npm run test -w components/o-layout
echo 849 && npm run test -w components/o-layout
echo 850 && npm run test -w components/o-layout
echo 851 && npm run test -w components/o-layout
echo 852 && npm run test -w components/o-layout
echo 853 && npm run test -w components/o-layout
echo 854 && npm run test -w components/o-layout
echo 855 && npm run test -w components/o-layout
echo 856 && npm run test -w components/o-layout
echo 857 && npm run test -w components/o-layout
echo 858 && npm run test -w components/o-layout
echo 859 && npm run test -w components/o-layout
echo 860 && npm run test -w components/o-layout
echo 861 && npm run test -w components/o-layout
echo 862 && npm run test -w components/o-layout
echo 863 && npm run test -w components/o-layout
echo 864 && npm run test -w components/o-layout
echo 865 && npm run test -w components/o-layout
echo 866 && npm run test -w components/o-layout
echo 867 && npm run test -w components/o-layout
echo 868 && npm run test -w components/o-layout
echo 869 && npm run test -w components/o-layout
echo 870 && npm run test -w components/o-layout
echo 871 && npm run test -w components/o-layout
echo 872 && npm run test -w components/o-layout
echo 873 && npm run test -w components/o-layout
echo 874 && npm run test -w components/o-layout
echo 875 && npm run test -w components/o-layout
echo 876 && npm run test -w components/o-layout
echo 877 && npm run test -w components/o-layout
echo 878 && npm run test -w components/o-layout
echo 879 && npm run test -w components/o-layout
echo 880 && npm run test -w components/o-layout
echo 881 && npm run test -w components/o-layout
echo 882 && npm run test -w components/o-layout
echo 883 && npm run test -w components/o-layout
echo 884 && npm run test -w components/o-layout
echo 885 && npm run test -w components/o-layout
echo 886 && npm run test -w components/o-layout
echo 887 && npm run test -w components/o-layout
echo 888 && npm run test -w components/o-layout
echo 889 && npm run test -w components/o-layout
echo 890 && npm run test -w components/o-layout
echo 891 && npm run test -w components/o-layout
echo 892 && npm run test -w components/o-layout
echo 893 && npm run test -w components/o-layout
echo 894 && npm run test -w components/o-layout
echo 895 && npm run test -w components/o-layout
echo 896 && npm run test -w components/o-layout
echo 897 && npm run test -w components/o-layout
echo 898 && npm run test -w components/o-layout
echo 899 && npm run test -w components/o-layout
echo 900 && npm run test -w components/o-layout
echo 901 && npm run test -w components/o-layout
echo 902 && npm run test -w components/o-layout
echo 903 && npm run test -w components/o-layout
echo 904 && npm run test -w components/o-layout
echo 905 && npm run test -w components/o-layout
echo 906 && npm run test -w components/o-layout
echo 907 && npm run test -w components/o-layout
echo 908 && npm run test -w components/o-layout
echo 909 && npm run test -w components/o-layout
echo 910 && npm run test -w components/o-layout
echo 911 && npm run test -w components/o-layout
echo 912 && npm run test -w components/o-layout
echo 913 && npm run test -w components/o-layout
echo 914 && npm run test -w components/o-layout
echo 915 && npm run test -w components/o-layout
echo 916 && npm run test -w components/o-layout
echo 917 && npm run test -w components/o-layout
echo 918 && npm run test -w components/o-layout
echo 919 && npm run test -w components/o-layout
echo 920 && npm run test -w components/o-layout
echo 921 && npm run test -w components/o-layout
echo 922 && npm run test -w components/o-layout
echo 923 && npm run test -w components/o-layout
echo 924 && npm run test -w components/o-layout
echo 925 && npm run test -w components/o-layout
echo 926 && npm run test -w components/o-layout
echo 927 && npm run test -w components/o-layout
echo 928 && npm run test -w components/o-layout
echo 929 && npm run test -w components/o-layout
echo 930 && npm run test -w components/o-layout
echo 931 && npm run test -w components/o-layout
echo 932 && npm run test -w components/o-layout
echo 933 && npm run test -w components/o-layout
echo 934 && npm run test -w components/o-layout
echo 935 && npm run test -w components/o-layout
echo 936 && npm run test -w components/o-layout
echo 937 && npm run test -w components/o-layout
echo 938 && npm run test -w components/o-layout
echo 939 && npm run test -w components/o-layout
echo 940 && npm run test -w components/o-layout
echo 941 && npm run test -w components/o-layout
echo 942 && npm run test -w components/o-layout
echo 943 && npm run test -w components/o-layout
echo 944 && npm run test -w components/o-layout
echo 945 && npm run test -w components/o-layout
echo 946 && npm run test -w components/o-layout
echo 947 && npm run test -w components/o-layout
echo 948 && npm run test -w components/o-layout
echo 949 && npm run test -w components/o-layout
echo 950 && npm run test -w components/o-layout
echo 951 && npm run test -w components/o-layout
echo 952 && npm run test -w components/o-layout
echo 953 && npm run test -w components/o-layout
echo 954 && npm run test -w components/o-layout
echo 955 && npm run test -w components/o-layout
echo 956 && npm run test -w components/o-layout
echo 957 && npm run test -w components/o-layout
echo 958 && npm run test -w components/o-layout
echo 959 && npm run test -w components/o-layout
echo 960 && npm run test -w components/o-layout
echo 961 && npm run test -w components/o-layout
echo 962 && npm run test -w components/o-layout
echo 963 && npm run test -w components/o-layout
echo 964 && npm run test -w components/o-layout
echo 965 && npm run test -w components/o-layout
echo 966 && npm run test -w components/o-layout
echo 967 && npm run test -w components/o-layout
echo 968 && npm run test -w components/o-layout
echo 969 && npm run test -w components/o-layout
echo 970 && npm run test -w components/o-layout
echo 971 && npm run test -w components/o-layout
echo 972 && npm run test -w components/o-layout
echo 973 && npm run test -w components/o-layout
echo 974 && npm run test -w components/o-layout
echo 975 && npm run test -w components/o-layout
echo 976 && npm run test -w components/o-layout
echo 977 && npm run test -w components/o-layout
echo 978 && npm run test -w components/o-layout
echo 979 && npm run test -w components/o-layout
echo 980 && npm run test -w components/o-layout
echo 981 && npm run test -w components/o-layout
echo 982 && npm run test -w components/o-layout
echo 983 && npm run test -w components/o-layout
echo 984 && npm run test -w components/o-layout
echo 985 && npm run test -w components/o-layout
echo 986 && npm run test -w components/o-layout
echo 987 && npm run test -w components/o-layout
echo 988 && npm run test -w components/o-layout
echo 989 && npm run test -w components/o-layout
echo 990 && npm run test -w components/o-layout
echo 991 && npm run test -w components/o-layout
echo 992 && npm run test -w components/o-layout
echo 993 && npm run test -w components/o-layout
echo 994 && npm run test -w components/o-layout
echo 995 && npm run test -w components/o-layout
echo 996 && npm run test -w components/o-layout
echo 997 && npm run test -w components/o-layout
echo 998 && npm run test -w components/o-layout
echo 999 && npm run test -w components/o-layout
echo 1000 && npm run test -w components/o-layout
